# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: scmo1
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ShuiApp

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: ${env:IAM_ROLE}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://87ua2ygez2.execute-api.eu-north-1.amazonaws.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT

  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  getAllNotes:
    handler: functions/getAllNotes/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: GET

  getNoteByNoteId:
    handler: functions/getNoteByNoteId/index.handler
    events:
      - httpApi:
          path: /api/note/{noteId}
          method: GET

  postNote:
    handler: functions/postNote/index.handler
    events:
      - httpApi:
          path: /api/note
          method: POST

  getNoteByUser:
    handler: functions/getNoteByUser/index.handler
    events:
      - httpApi:
          path: /api/notes/user/{username}
          method: GET

  editNote:
    handler: functions/editNote/index.handler
    events:
      - httpApi:
          path: /api/note/{noteId}
          method: PUT

resources:
  Resources:
    ShuiAppTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ShuiNotesTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: usernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
